services:
  PrestaShop\Module\DashProducts\Controller\ConfigurationController:
    public: true
    autowire: true
    autoconfigure: true

  PrestaShop\Module\DashProducts\Type\ConfigurationType:
    tags: ['form.type']
